### PR TITLE
Feature/razor library

### LINKED ISSUE #206: Razor class library
Recently done this on my SeoToolkit package and Umbraco also does this. Would be nice to move all the static assets to a razor class library. We can use the changes in SeoToolkit (https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/102) as a guideline. Mostly just adding some package manifest in code and some tags to the csproj files.

### PR DESCRIPTION
**Pull request by patrickdemooij9**
Fixes https://github.com/TimGeyssens/UIOMatic/issues/206

- [x] Change project to Razor Library
- [x] Move package manifest to C# class
- [x] Move all property editors to C#
- [x] pickers.property.controller.js seems to not work anymore for the dropdown.
- [x] Test the build to see if it works as expected

### CODE REVIEW

**Comment by patrickdemooij9** [comment]
~~@TimGeyssens is it possible to get the nuget artifact from appveyor? I want to test if the razor class library (with all files) successfully goes through the build~~

Nvm. I see that I can just access it through appveyor itself!

**Comment by patrickdemooij9** [comment]
Will update this PR with the changes regarding the file structure, so please don't merge yet :)

**Comment by TimGeyssens** [comment]
sure just merge when it is ready! awesome work!

**Comment by patrickdemooij9** [comment]
Whoops! @TimGeyssens, I accidently published this package in your name: https://www.nuget.org/packages/UIOMatic. I'll remove the deploy step from the appveyor for now until the build is all good to go

**Pull request merged**
