### PR TITLE
v2

### PR DESCRIPTION
**Pull request by mattbrailsford**
Huuuuuuuuge updates. Please spend time reviewing before accepting. Not all views are fully tested. Build scripts will need updating to work with appveryor. Docs / readme probably need updating also.

### CODE REVIEW

**Comment by TimGeyssens** [comment]
This is so awesome :), just starting to review, be sure to update the readme and package/Nuget info with your details since I don't wanna take credit for your amazing effort!

**Comment by mattbrailsford** [comment]
Haha, sure thing :)

Been tons of fun playing around with it. I know I've tweaked a lot, but quite a bit of that was just house keeping and then introducing a few new concepts, so hope you don't mind all the changes I made :)

**Comment by TimGeyssens** [comment]
Nope I definitely don't mind, lot's to learn from :) Yay open source and contributions!

**Comment by TimGeyssens** [comment]
Oh my so much goodness, spend a couple of hours testing and core functionality seems to be running fine :) love all the enhancements! Seems only a few minor issues with wrong paths due to restructure but can fix those, and of course docs need  thorough updating but can do that as part of further testing

**Pull request merged**
