### PR TITLE
Content apps

### PR DESCRIPTION
**Pull request by skartknet**
This PR tackles issue #161 

I have been able to adapt the editor view to support content apps. For this to work I have created a IUiomaticContentAppFactory, a UiomaticEditorContentAppFactory and a UiomaticContentAppFactoryCollection. These are based on Umbraco's code for content apps but adapted to support Types.

I got it kind of working to a point but I got stuck in displaying the selected item in the editor app. On the Umbraco documentation says that we can use editorState to retrieve the id of the node but obviously in UIOmatic we don;t have editorState so I don't know how to pass the node information to the apps.

image

Well, these are my 2cts, hopefully someone can give me a hand.

### CODE REVIEW

**Comment by TimGeyssens** [comment]
Hey, you should be able to just inject editorState and use it...

**Comment by TimGeyssens** [comment]
Check the docs here: https://our.umbraco.com/documentation/Extending/Content-Apps/ so in your content app controller

add editorState as a function param and then you should be able to get the id with  editorState.current.id;

**Comment by TimGeyssens** [comment]
Great PR btw, thanks!

**Comment by TimGeyssens** [comment]
It would be ace if the content app and the list prop editor and the list editor was reusing the same directive but for now I'm also happy with a copy... you could actually refactor this one into what you need https://github.com/TimGeyssens/UIOMatic/blob/v3/src/UIOMatic/Web/UI/App_Plugins/UIOMatic/backoffice/views/propertyeditors/listview.controller.js

**Comment by skartknet** [comment]
I have tried getting the editorState but `editorState.current` is null (editorState is not null, so something is being injected here). 
https://github.com/TimGeyssens/UIOMatic/blob/27f4883148fabd1995e6abe8da258d9c34c0b3d3/src/UIOMatic/Web/UI/App_Plugins/UIOMatic/backoffice/apps/uiomaticContent.controller.js#L1-L5

**Comment by skartknet** [comment]
I found how to do it. In the edit controller you can set any values to the editorState with `editorState.set(values)`

**Comment by TimGeyssens** [comment]
Cool, let me know when you have it working

**Comment by skartknet** [comment]
Hey @TimGeyssens sorry it has taken me a while to revisit this. The apps are working now. Please take a look.

**Comment by TimGeyssens** [comment]
No need to say sorry @skartknet , I love that you take the time to contribute! And hey now it counts as a hacktober fest contrib 👍

**Comment by TimGeyssens** [comment]
Would it be ok to also write some docs on how folks can use the content app? Or if you write some details here I can add them to the general docs :) Just how you can add them on your doc types...

**Comment by TimGeyssens** [comment]
Awesome with the docs! Thanks

**Pull request merged**
