### PR TITLE
Umbraco 10 version

### PR DESCRIPTION
**Pull request by patrickdemooij9**
Hi @TimGeyssens 

Tried to contact you on Twitter about this, but didn't receive an answer so I just got started on the v10 version.
However, this isn't only about making it v10 compatible. The v9 version has a LOT of issues that I also want to fix with this PR. The PR is still a draft as there are still a lot of things uncomment and just not working.

- [x] V10 support
- [x] Make sure that static assets (HTML, CSS, JS, Translations) are actually copied over.
- [x] Fix the error on every node
- [x] Fix random person data node being shown in UIOMatic section
- [x] Make the UIOMatic section actually work
- [x] Make UIOMatic work without any configuration needed
- [x] Other bugs I find
- [x] https://github.com/TimGeyssens/UIOMatic/issues/196
- [x] Migrations

Also, could you make a v5 branch for me so I can push this there?

### CODE REVIEW

**Comment by TimGeyssens** [comment]
awesome @patrickdemooij9 , I added you as a collab so you can create the branch and merge pull requests :)

**Comment by TimGeyssens** [comment]
this might be a good one to consider in the v5 version: https://github.com/TimGeyssens/UIOMatic/issues/196

**Comment by patrickdemooij9** [comment]
> this might be a good one to consider in the v5 version: #196

Yes, I will take a look at that one too. Would be nice to have

**Comment by patrickdemooij9** [comment]
@TimGeyssens
I am currently working on fixing the migration and I have a question regarding `AddSummaryDashboardToConfig `and `InstancePing`. What do they do and are they still needed?

**Comment by TimGeyssens** [comment]
@patrickdemooij9 you can remove instance ping... for the AddSummaryDashboardToConfig... it can probably be done without a migration? It is just so the section has a dashboard

**Comment by TimGeyssens** [comment]
fyi if you want appveyor to build just change the version number to 5.0.0 in this file 

https://github.com/TimGeyssens/UIOMatic/blob/v5/appveyor.yml

so should become 

# version format
version: 5.0.0.{build}

# environment
environment:
  majorversion: 5
  minorversion: 0
  patchversion: 0

**Comment by patrickdemooij9** [comment]
Appveyor should hopefully work with the latest commits now :)
Also, the latest changes should also fix https://github.com/TimGeyssens/UIOMatic/issues/196. It does however come with a breaking change if people implemented custom editors, so we should probably put that in the release notes later on.

And ideally, we would replace some of the current custom editors with the editors of Umbraco as they will most likely be very similar now, but that can be done another time

**Comment by TimGeyssens** [comment]
wow great job!

**Pull request merged**
