### PR TITLE
Listview datatype

### PR DESCRIPTION
**Pull request by rasmusfjord**
Shit load of hours later i present the listview datatype.

The idea is you have a PetaPoco model but its "bound" to a node, an example is you create a "team" as a node but all the members is better placed on a PocoModel instead of subnodes. Now you want the power of UI-O-Matic but only want it shown on a single nodetype where the team context is so you can give an even better UI experience.

So you setup your datatype:
image

Options are:

- Select petapoco object
- Select the property that holds the nodeId (Which will be saved on create)
- Sort and sort order 
- A whole lot of hide properties to make a smaller list
- Filters, here you can set some predefined filters like in the above screenshot I only want to show teammembers which are on GuestList, not deleted and not on waitlist.

This gives these different views:
image
image

I have also created edit/create as a dialog instead, because in this context this gives more sense.
image

Right now the nodeId Property is needed, but it would be very easy to make it optional so you could show all of a type.

### CODE REVIEW

**Comment by TimGeyssens** [comment]
Again awesome work 👍  , will review asap!

**Comment by rasmusfjord** [comment]
Thx man! Yeah a review would be good :) Never used UIoMatic before so prob destroyed some principles :)

**Comment by TimGeyssens** [comment]
Just thinking out loud here but what if instead of having another GetPaged method with the nodeId param we simply supply the filter with all of the options we need

So could be something like Teamid|{{nodeId}}  (not sure about the syntax but hope you get the point...) we can also introduce some other shortcuts {{parentId}}, {{siteId}}, ... might be a bit more hassle to set things up for the dev but it will add some flexibility

**Comment by rasmusfjord** [comment]
I was thinking the exact same thing actually, after i had done all the rest and thought out the filter extension :)

At the moment i dont have the time to extend it that way but i find it super cool! Maybe if you could give med a way to handle the {{nodeId}} shortcut/contextproperties we could figure something out.

**Comment by TimGeyssens** [comment]
Ok then I think we agree that is the way forward :) @mattbrailsford anything you want to add?

**Comment by rasmusfjord** [comment]
Super :) if you come up with a way to handle the {{nodeId}} kinda tags, i will easily redo the code to clean up the GetPaged, and get it hooked into the javascript.

**Comment by TimGeyssens** [comment]
Still on the todo, sorry this is taking so long, but really ❤️  the contribution :)

**Comment by rasmusfjord** [comment]
Sure thing :)

Med venlig hilsen
----
Rasmus Fjord

42407620

On 25-04-2017 16:19:25, Tim Geyssens <notifications@github.com> wrote:
Still on the todo, sorry this is taking so long, but really ❤️ the contribution :)

**Comment by rasmusfjord** [comment]
Should we hack this together at codegarden?

**Pull request merged**
